[package]
name = "helios-ui"
version.workspace = true
edition.workspace = true
description = "Optional web UI for the Helios FHIR Server"
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage = "https://github.com/HeliosSoftware/hfs/tree/main/crates/ui"
keywords = ["helios-software", "fhir", "ui", "htmx"]

[dependencies]
axum = "0.8"
