#!/bin/bash
# T6 as Angela (View Definitions page requests with her session) + $sql-run via the API (service token)
source /home/angela/pass-1182/env.sh; unset CURL_HOME; cd $WORK; S=$(cat private/session.id); PID=7d24f7a0-6f2e-ce3b-5568-db7b14695583
H=(-b "hfs_session=$S" -H 'Sec-Fetch-Site: same-origin')
txt(){ python3 -c 'import sys,re,html; t=sys.stdin.read(); t=re.sub(r"<script.*?</script>","",t,flags=re.S); print(html.unescape(re.sub(r"\s+"," ",re.sub(r"<[^>]+>"," ",t))).strip()[:int(sys.argv[1])])' ${1:-300}; }
save_vd(){ curl -s -o /dev/null -D /tmp/sv.hdr -w '%{http_code}' -X POST "${H[@]}" --data-urlencode "json@$1" --data action=save --data id= "$HFS/ui/sql/view-definitions"; }
echo "## T6 $(date -u +%FT%TZ)"
for fx in vd-patient vd-obs; do printf "save %s -> %s " $fx $(save_vd fixtures/$fx.json); L=$(grep -i '^location' /tmp/sv.hdr | tr -d '\r' | awk '{print $2}'); echo "$L"; id=$(echo "$L" | grep -o 'vd=[^&]*' | cut -d= -f2); [ $fx = vd-patient ] && VD=$id || VD2=$id; done
echo "VD=$VD VD2=$VD2" > run/t6-ids.env
echo "### Results card (POST /ui/sql/view-definitions/run)"; for fx in vd-patient vd-obs; do printf '%s: ' $fx; curl -s -X POST "${H[@]}" --data-urlencode "json@fixtures/$fx.json" "$HFS/ui/sql/view-definitions/run" | txt 260; done
echo "### lint: \"column\" -> \"colum\""; sed 's/"column"/"colum"/' fixtures/vd-patient.json > /tmp/vd-typo.json; curl -s -X POST "${H[@]}" -H 'Content-Type: application/json' --data-binary @/tmp/vd-typo.json "$HFS/ui/sql/view-definitions/lint" | python3 -c 'import sys,json; d=json.load(sys.stdin); L=d if isinstance(d,list) else d.get("diagnostics",d); print([ (x.get("message"),[f.get("title") or f.get("label") for f in x.get("fixes",x.get("actions",[]))]) for x in L][:3])'
echo "### completion: getRes"; python3 - <<'PY' > /tmp/cmp.json
import json; d=json.load(open('/home/angela/pass-1182/fixtures/vd-patient.json')); d['select'][0]['column'][0]['path']='getRes'
print(json.dumps({"kind":"fhirpath","pointer":"/select/0/column/0/path","document":d,"expression":"getRes","cursor":6}))
PY
curl -s -X POST "${H[@]}" -H 'Content-Type: application/json' --data-binary @/tmp/cmp.json "$HFS/ui/sql/view-definitions/complete" | python3 -c 'import sys,json; d=json.load(sys.stdin); it=d if isinstance(d,list) else d.get("options",d.get("items",[])); print("offers getResourceKey():", any("getResourceKey" in (x.get("label","") if isinstance(x,dict) else str(x)) for x in it), [ (x.get("label") if isinstance(x,dict) else x) for x in it][:6])'
echo "### rail ?filter=patient"; curl -s "${H[@]}" "$HFS/ui/sql/view-definitions?filter=patient" | grep -o 'filter-rail__label">[^<]*' | sort -u | sed 's/.*">/  /'
echo "### duplicate + delete"; printf 'duplicate -> %s ' $(curl -s -o /dev/null -D /tmp/du.hdr -w '%{http_code}' -X POST "${H[@]}" --data-urlencode "json@fixtures/vd-patient.json" --data action=duplicate --data id=$VD "$HFS/ui/sql/view-definitions"); DUP=$(grep -i '^location' /tmp/du.hdr | grep -o 'vd=[^&]*' | cut -d= -f2); echo "copy $DUP"; curl -s -H 'Accept: application/fhir+json' "${H[@]}" "$HFS/ViewDefinition/$DUP" | python3 -c 'import sys,json;print("  copy name:",json.load(sys.stdin).get("name"))'; printf '  DELETE /ViewDefinition/copy (editor request) -> %s\n' $(curl -s -o /dev/null -w '%{http_code}' -X DELETE "${H[@]}" "$HFS/ViewDefinition/$DUP"); printf '  GET copy after -> %s\n' $(curl -s -o /dev/null -w '%{http_code}' "${H[@]}" "$HFS/ViewDefinition/$DUP")
echo "### negative resource Nope"; sed 's/"resource": "Patient"/"resource": "Nope"/; s/"resource":"Patient"/"resource":"Nope"/' fixtures/vd-patient.json > /tmp/vd-nope.json; curl -s -X POST "${H[@]}" --data-urlencode "json@/tmp/vd-nope.json" "$HFS/ui/sql/view-definitions/run" | txt 200
echo "### \$sql-run (API, service token)"; T=$(etok hfs); B="{\"resourceType\":\"Parameters\",\"parameter\":[{\"name\":\"subjectReference\",\"valueReference\":{\"reference\":\"ViewDefinition/$VD\"}}]}"
for fmt in json text/csv application/ndjson application/parquet; do f=run/t6-sqlrun.$(echo $fmt|tr / _); printf '%-20s -> ' $fmt; curl -s -o $f -w '%{http_code} %{time_total}s %{size_download}B ' -X POST -H "Authorization: Bearer $T" -H 'Content-Type: application/json' -d "$B" "$HFS/\$sql-run?_format=$fmt"; case $fmt in json) python3 -c "import json;d=json.load(open('$f'));print('rows',len(d),'cols',sorted(d[0]))";; text/csv) echo "rows $(($(wc -l<$f)-1)) PID: $(grep $PID $f)";; application/ndjson) echo "rows $(grep -c . $f)";; *) echo "rows $(/home/angela/manual-test-1179/venv/bin/python -c "import pyarrow.parquet as pq;print(pq.ParquetFile('$f').metadata.num_rows)")";; esac; done
BP="{\"resourceType\":\"Parameters\",\"parameter\":[{\"name\":\"subjectReference\",\"valueReference\":{\"reference\":\"ViewDefinition/$VD\"}},{\"name\":\"patient\",\"valueReference\":{\"reference\":\"Patient/$PID\"}}]}"
printf 'patient=PID -> '; curl -s -X POST -H "Authorization: Bearer $T" -H 'Content-Type: application/json' -d "$BP" "$HFS/\$sql-run?_format=json" | head -c 200; echo
printf 'no token -> '; curl -s -o /tmp/n.out -w '%{http_code} ' -X POST -H 'Content-Type: application/json' -d "$B" "$HFS/\$sql-run?_format=json"; head -c 120 /tmp/n.out; echo
echo "## T6 done $(date -u +%FT%TZ)"
