[package]
name = "fhir"
version = "0.1.0"
edition = "2021"

[features]
default = ["R4"]
R4 = []
R4B = []
R5 = []
R6 = []

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
zip = "0.6"
